name: oktoast
description: A pure flutter toast library, support custom style/widget, easy achieve the same effect with native toasts.
email: cjl_spy@163.com
homepage: https://github.com/OpenFlutter/flutter_oktoast
version: 4.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.13.0-0.0.pre.364" # Support for 120fps on iOS

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
